apiVersion: v1
kind: Service
metadata:
  name: go-gs-service
spec:
  selector:
    app: go-gracefull-shutdown
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3333
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: go-gracefull-shutdown
spec:
  replicas: 2
  selector:
    matchLabels:
      app: go-gracefull-shutdown
  template:
    metadata:
      labels:
        app: go-gracefull-shutdown
    spec:
      terminationGracePeriodSeconds: 60
      containers:
      - name: go-gracefull-shutdown
        image: meziaris/go-gracefull-shutdown:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3333
        livenessProbe:
          httpGet:
            path: /health
            port: 3333
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 3333
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        lifecycle:
          preStop:
            exec:
              command: ["/bin/sh", "-c", "sleep 5"]
        resources:
          requests:
            memory: "128Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
